SELECT COLUMN_NAME, DATA_TYPE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'customer';
--Q1. What is the total revenue generated by male vs. female customers?
--Q2. Which customers used a discount but still spent more than the average purchase amount?
--Q3. Which are the top 5 products with the highest average review rating? 
--Q4. Compare the average Purchase Amounts between Standard and Express Shipping.
--Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.
--Q6. Which 5 products have the highest percentage of purchases with discounts applied? 
--Q7. Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment.
--Q8. What are the top 3 most purchased products within each category?
--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
--Q10. What is the revenue contribution of each age group?

-- Question 1
select gender, sum(purchase_amount) as total_revenue 
from customer
group by gender;

-- Question 2
select customer_id, purchase_amount from customer 
where discount_applied = 'Yes' AND (select avg(purchase_amount) from customer)<=purchase_amount;

--Question 3
select item_purchased, ROUND(AVG(review_rating::numeric),2) as "Average_review_rating" from customer
group by item_purchased
order by avg(review_rating) desc limit 5;

--Question 4
select shipping_type, Round(avg(purchase_amount),2) as "avg_amount" from customer
where shipping_type IN ('Express', 'Standard')
group by shipping_type;

--Question 5
SELECT COUNT(customer_id) AS "total_customers",
ROUND(AVG(purchase_amount),2) AS "average_spent", 
ROUND(SUM(purchase_amount),2) AS "total_revenue",
subscription_status 
FROM customer
GROUP BY subscription_status
ORDER BY total_revenue, average_spent desc;

--Question 6
select item_purchased,
ROUND(100 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)/COUNT(*),2) AS discount_rate
FROM customer 
GROUP BY item_purchased
ORDER BY discount_rate DESC
limit 5;

--Question 7
with customer_type as (
	SELECT customer_id, previous_purchases, 
	CASE WHEN previous_purchases = 1 THEN 'New'
	WHEN previous_purchases BETWEEN 2 and 10 THEN 'Returning'
	ELSE 'Loyal'
	END AS customer_segment
FROM customer
)

select customer_segment, COUNT(*) AS "no_of_customers"
FROM customer_type
GROUP BY customer_segment;

--Question 8
with item_counts as (
select category,
item_purchased,
count(customer_id) as total_orders,
ROW_NUMBER() over(partition by category order by count(customer_id) DESC) as item_rank
from customer
group by category, item_purchased
)

select item_rank, category, item_purchased, total_orders
from item_counts
where item_rank <= 3;

--Question 9
select subscription_status,
count(customer_id) as repeat_buyers
from customer
where previous_purchases > 5
group by subscription_status;

--Question 10
select age_group,
SUM(purchase_amount) as "total_revenue"
from customer
group by age_group
order by total_revenue;